// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Portfolio_LogIn', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Portfolio_LogIn', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 550, height: 692 })
    {
      const element = await driver.findElement(By.css("a:nth-child(5) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css("a:nth-child(4) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css("a:nth-child(7) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("a:nth-child(8) > .MuiButtonBase-root")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("password")).sendKeys("dbs3508!")
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("email")).sendKeys("gyoon1@my.centennialcollege.ca")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.css("a:nth-child(7) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("a:nth-child(8) > .MuiButtonBase-root")).click()
    await driver.findElement(By.css("a:nth-child(7) > .MuiButtonBase-root")).click()
    await driver.findElement(By.id("name")).click()
    {
      const element = await driver.findElement(By.css("a:nth-child(8) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("a:nth-child(8) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("password")).sendKeys("dbs3508!")
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("email")).sendKeys("gyoon1@my.centennialcollege.ca")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.css("a:nth-child(8) > .MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("a:nth-child(8) > .MuiButtonBase-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("gyoon1@my.centennialcollege.ca")
    await driver.findElement(By.id("password")).sendKeys("dbs3508!")
    await driver.findElement(By.css(".MuiCardActions-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.css(".css-yb0rsr"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
