// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SingUp', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SingUp', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.css("a:nth-child(7) > .MuiButtonBase-root")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("example")
    await driver.findElement(By.id("email")).sendKeys("example@example.com")
    await driver.findElement(By.id("password")).sendKeys("example")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    // 회원가입 성공 후 특정 요소가 보이는지 검증
    let successElem = await driver.wait(
      until.elementLocated(By.css(".MuiTypography-h6")),
      5000
    )
    let text = await successElem.getText()
    assert.ok(text.length > 0, "회원가입 후 페이지에 텍스트가 보여야 합니다.")
  })
})
