# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPortfolioLogIn():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_portfolioLogIn(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(550, 692)
    # 로그인 페이지 이동 및 입력
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(8) > .MuiButtonBase-root").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("gyoon1@my.centennialcollege.ca")
    self.driver.find_element(By.ID, "password").send_keys("dbs3508!")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained").click()
    # 로그인 성공 후 특정 요소가 보이는지 검증
    time.sleep(2)
    success_elem = self.driver.find_element(By.CSS_SELECTOR, ".MuiTypography-h6")
    assert success_elem.text != "", "로그인 후 페이지에 텍스트가 보여야 합니다."

